name: PROD Manual Trigger - Workflow

#Triggers manually
#APPROVAL is needed for all the jobs to trigger !!!
on:
  workflow_dispatch:
    inputs:
      isPolicyNeeded:
        description: 'Flag to decide if policy execution is needed'     
        required: true
        default: 'true'

jobs:
  #Pre deployment Job
  pre-deploy-prod-01:
      runs-on: ubuntu-20.04
      environment:
        name: "PROD"
      outputs:
        output1: ${{ steps.RunScriptFile.outputs.API_ID }}
      steps:
      - uses: actions/checkout@v2
      - id: RunScriptFile
        run: |
         npm install -g anypoint-cli-v4
         sudo apt-get update && sudo apt-get -qq -y install jq  
         sudo apt install libxml2-utils
         chmod +x scripts/deploymentAutomationScript.sh
         ./scripts/deploymentAutomationScript.sh "PROD" ${{ secrets.MULE_HG_CLI_CLIENT_ID }} ${{ secrets.MULE_HG_CLI_CLIENT_SECRET }} ${{ secrets.MULE_PARENT_BIZ_GROUP }} pom.xml ${{ vars.DEPLOYMENT_TYPE }} ${{ vars.PRE_DEPLOYMENT_ACTION }} > ./result.txt
         cat result.txt
         echo "API_ID=$(cat result.txt | grep "APIId:" | cut -d":" -f2)" >> $GITHUB_OUTPUT
        shell: bash 
        
  #This job deploys the application to PROD environment with provided configuration details; upon APPROVAL from the aprrovers
  deploy-prod-01:
    needs: pre-deploy-prod-01
    uses: am-cicd/ms-devops-workflow-main/.github/workflows/deploy_workflow.yml@feature/pldt
    with:
      CLOUDHUB_ENVIRONMENT: "PROD"
      GITHUB_ENVIRONMENT: "PROD"
      CLOUDHUB_REPLICAS: "${{ vars.MULE_CLOUDHUB_REPLICAS_1 }}"
      CLOUDHUB_REPLICA_SIZE: "${{ vars.MULE_CLOUDHUB_REPLICA_SIZE_0_1 }}"
      CLOUDHUB_PRIVATE_SPACE: "${{ vars.MULE_PROD_CLOUDHUB_PRIVATE_SPACE }}"
      CLOUDHUB_PUBLIC_URL: "" #Provide the Endpoint URL if custom public endpoint is needed
      GENERATE_PUBLIC_URL_FLAG: "false" #Set to true only if the app has public Endpoint URL; in all other cases this should be false
      APP_LAYER: ${{ vars.MULE_SYS_API_LAYER }}
      APP_VERSION: "v1"
      API_ID: "${{ needs.pre-deploy-prod-01.outputs.output1 }}"
      CLUSTER_ENABLED_FLAG: "false" #Set to true if needed;
    secrets:
      EX_CONNECTED_APP_ID: "${{ secrets.MULE_EX_CONNECTED_APP_ID }}"
      EX_CONNECTED_APP_SECRET: "${{ secrets.MULE_EX_CONNECTED_APP_SECRET }}"
      CH_CONNECTED_APP_ID: "${{ secrets.MULE_PROD_CH_CONNECTED_APP_ID }}"
      CH_CONNECTED_APP_SECRET: "${{ secrets.MULE_PROD_CH_CONNECTED_APP_SECRET }}"
      MULE_AP_CLIENT_ID: "${{ secrets.MULE_AP_CLIENT_ID }}"
      MULE_AP_CLIENT_SECRET: "${{ secrets.MULE_AP_CLIENT_SECRET }}"
      BIZ_GROUP: "${{ secrets.MULE_PARENT_BIZ_GROUP }}"
      SECURE_ENCRYPT_KEY: "${{ secrets.MULE_PROD_SECURE_ENCRYPT_KEY }}"

  #Post Deployment Job
  post-deploy-prod-01:
    if: ${{ github.event.inputs.isPolicyNeeded == '' || github.event.inputs.isPolicyNeeded == 'true' }}
    runs-on: ubuntu-20.04
    needs: deploy-prod-01
    environment:
      name: "PROD"
    env:
      policyFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/policies.yaml"
    steps:
    - uses: actions/checkout@v2
    - id: RunPostDeploymentScriptFile
      run: |
         npm install -g anypoint-cli-v4
         sudo apt-get update && sudo apt-get -qq -y install jq  
         sudo apt install libxml2-utils
         sudo snap install yq
         chmod +x scripts/deploymentAutomationScript.sh
         ./scripts/deploymentAutomationScript.sh "PROD" ${{ secrets.MULE_HG_CLI_CLIENT_ID }} ${{ secrets.MULE_HG_CLI_CLIENT_SECRET }} ${{ secrets.MULE_PARENT_BIZ_GROUP }} pom.xml ${{ vars.DEPLOYMENT_TYPE }} ${{ vars.POST_DEPLOYMENT_ACTION }} $policyFile
      shell: bash
